# Source - https://stackoverflow.com/a/77024763
# Posted by El farouk, modified by community. See post 'Timeline' for change history
# Retrieved 2026-02-05, License - CC BY-SA 4.0

[pytest]

DJANGO_SETTINGS_MODULE=core.settings
python_files = tests.py test_*.py *_tests.py
