# Generated by Django 5.2.8 on 2026-01-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders_app.orderfeatures'),
        ),
    ]
