# Generated by Django 5.2.8 on 2026-01-03 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_remove_offerdetail_url_and_more'),
        ('orders_app', '0003_alter_order_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='offers_app.offer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='order_features', to='orders_app.orderfeatures'),
        ),
    ]
