# Generated by Django 5.2.8 on 2026-01-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0005_alter_order_revisions_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time_in_days',
            field=models.IntegerField(default=0),
        ),
    ]
