# Generated by Django 5.2.8 on 2026-01-06 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_remove_offerdetail_url_and_more'),
        ('orders_app', '0009_alter_order_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='offers_app.offerdetail'),
        ),
    ]
