# Generated by Django 5.2.8 on 2026-01-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0010_order_offer_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=50),
        ),
    ]
