# Generated by Django 5.2.8 on 2026-01-30 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0012_alter_order_business_user_alter_order_customer_user'),
        ('profile_app', '0007_businessprofile_username_customerprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='business_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_business_profile', to='profile_app.businessprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_customer_profile', to='profile_app.customerprofile'),
        ),
    ]
