# Generated by Django 5.2.8 on 2025-12-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='DEFAULT', max_length=140)),
                ('username', models.CharField(default='DEFAULT', max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField()),
            ],
        ),
    ]
