# Generated by Django 5.2.8 on 2025-12-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_user_type_user_user_id_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='DEFAULT', max_length=140)),
                ('username', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('user_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
