# Generated by Django 5.2.8 on 2025-12-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_userprofile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='file',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tel',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.CharField(default='customer'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='working_hours',
            field=models.CharField(blank=True),
        ),
    ]
