# Generated by Django 5.2.8 on 2026-02-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
