# Generated by Django 5.2.8 on 2026-02-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_customuser_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='file',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
