# Generated by Django 5.2.8 on 2025-12-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_offer_created_at_offer_description_offer_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdetail',
            name='url',
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='delivery_time_in_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='offer_type',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='revisions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
