# Generated by Django 5.2.8 on 2026-01-07 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_remove_offerdetail_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdetail',
            name='user',
        ),
    ]
