# Generated by Django 5.2.8 on 2026-02-09 16:08

import django.db.models.deletion
from django.db import migrations, models


def clear_empty_image_values(apps, schema_editor):
    """Set empty string image values to NULL before converting to ForeignKey."""
    Offer = apps.get_model('offers_app', 'Offer')
    Offer.objects.filter(image='').update(image=None)


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0005_alter_offer_min_price'),
        ('upload_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clear_empty_image_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer', to='upload_app.fileupload'),
        ),
    ]
