# Generated by Django 5.2.8 on 2026-01-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
