# Generated by Django 5.2.8 on 2025-12-22 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_alter_businessprofile_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='type',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='username',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='type',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='username',
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
