# Generated by Django 5.2.8 on 2026-01-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_alter_businessprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='username',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='username',
        ),
    ]
