# Generated by Django 5.2.8 on 2026-01-27 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_businessprofile_first_name_businessprofile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='username',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='username',
        ),
    ]
