# Generated by Django 5.2.8 on 2026-01-31 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0007_businessprofile_username_customerprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='username',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='username',
        ),
    ]
