# Generated by Django 5.2.8 on 2026-01-10 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_info_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseinfo',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='baseinfo',
            name='business_profile_count',
        ),
        migrations.RemoveField(
            model_name='baseinfo',
            name='offer_count',
        ),
        migrations.RemoveField(
            model_name='baseinfo',
            name='review_count',
        ),
    ]
