# Generated by Django 5.2.8 on 2026-01-30 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0007_businessprofile_username_customerprofile_username'),
        ('reviews_app', '0003_alter_review_business_user_alter_review_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='business_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_business_user', to='profile_app.businessprofile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_customer_reviewer', to='profile_app.customerprofile'),
        ),
    ]
