# Generated by Django 5.2.8 on 2026-02-06 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0005_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
