# Generated by Django 5.2.8 on 2026-02-06 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0008_remove_businessprofile_file_and_more'),
        ('reviews_app', '0006_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('business_user', 'reviewer')},
        ),
    ]
